### ISSUE TITLE
Introduce definition of VM groups

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-azure-basic-infrastructure#13]
**Is your feature request related to a problem? Please describe.**
We need an option to specify VM groups. the use case example is when we have different Epiphany components and each of them requires VMs configured according to resources consumption.

**Describe the solution you'd like**
Add an ability to define VM groups and configure it with module parameters.
Parameters need to be defined for VM group:

* VM type (CPU, RAM)
* base OS image
* subnet id for the group that is taken from `subnets` parameter implemented in #46  task
* additional security group settings / instance profiles
* enable/disable public IP addresses
* at this stage we should not be using autoscaling groups for hadling single VMs (we made this mistake before)

**Describe alternatives you've considered**
No.

**Additional context**
Original task description:
We need to implement possibility of setting Virtual Machine Sizes when deploying epiphany in AWS, Azure, or OnPrem. New option vm_size should be introduced.
-> Originally posted by @mkyc in https://github.com/epiphany-platform/m-azure-basic-infrastructure/pull/12#discussion_r495448963_

**Comment by plirglo** [comment]
Looks rather straightforward. We should also inform user in manual what is default size of machine and what is minimal required machine size (if any).

**Comment by mkyc** [comment]
Yeah, it might make sense to provide sizes for each subnet as proposed in #14

**Comment by mum0l** [comment]
LGTM

**Comment by mkyc** [comment]
@mum0l I think little task description update would be nice.

**Comment by atsikham** [comment]
Should be groomed together with https://github.com/epiphany-platform/m-aws-basic-infrastructure/issues/27

**Comment by atsikham** [comment]
**Please take a look at #28 and #42. Probably they can be closed as there is similar functionality described**

**Comment by erzetpe** [comment]
Removing disk related part as this is a part of [#42](https://app.zenhub.com/workspaces/epiphany-platform-5ef9d3c749afc20019782391/issues/epiphany-platform/m-azure-basic-infrastructure/42).

**Comment by atsikham** [comment]
There is a bug mentioned in #63, so moving this task back to "In Progress".

**Comment by atsikham** [comment]
Should be tested together with #63

**Comment by rpudlowski93** [comment]
Tested with #63 - works fine

I created new infrastructure with two different subnets and two different vm groups. Each instance got its own public IP and it was possible to login to each instance using the public IP :) ✅

Only security groups are not customisable but it should be a part of the task #[52](https://github.com/epiphany-platform/m-azure-basic-infrastructure/issues/42)
