### ISSUE TITLE
Add to output id and ip range of vnet and subnets

### ISSUE THREAD

**Issue by pprach** [epiphany-platform/m-azure-basic-infrastructure#15]
Add to output following information about **all subnets** and **vnet**:
* id
* ip range

**Comment by atsikham** [comment]
Look's straightforward. @pprach is it about private/public/all subnets?

**Comment by pprach** [comment]
I've got sth like this in my mind: https://registry.terraform.io/modules/Azure/vnet/azurerm/2.3.0

**Comment by sk4zuzu** [comment]
@pprach we explicitly removed https://registry.terraform.io/modules/Azure/vnet/azurerm/2.3.0 module, it was used before. We strongly believe it's low quality one, also there is no good followup with AKS module in that group owned by MS. :)

**Comment by mkyc** [comment]
There is possibility to get following information directly from AzBI configuration: 
 - `Config.Params.Subnets[*].AddressPrefixes` for subnets ip ranges
 - `Config.Params.AddressSpace` for vnet ip range
 - `Output.VnetName` for vnet name

So AFAIU only names of subnets are missing from scope of this issue.

**Comment by ar3ndt** [comment]
nothing to do in this task imo. Subnet names  can be taken from AzBI configuration as well:

* Config.Params.Subnets[*].name
* Config.Params.Vm_groups[*].Subnet_names[*]

**Comment by mkyc** [comment]
Reviewed and looks that we do have all we need.
