### ISSUE TITLE
Add info how to destroy created resources in readme

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-azure-basic-infrastructure#19]
Verified that infrastructure created without any issues. But I would like to see how to destroy created resources in readme:

```bash
make destroy-plan
make destroy
```

_Originally posted by @atsikham in https://github.com/epiphany-platform/epiphany/issues/1622#issuecomment-702662286_

**Comment by przemyslavic** [comment]
I was able to delete the created resources by following the provided instructions.
