### ISSUE TITLE
Module tests fixes

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-azure-basic-infrastructure#26]
@mkyc what I found, can be fixed in other tasks:
* Test report file name is `repot.xml`, shouldn't it be `report.xml`?
* No description about dependencies that should be installed to run tests, such as `go`, `go-junit-report`, `yq`.
* Licenses information is not updated according to the point above.

_Originally posted by @atsikham in https://github.com/epiphany-platform/epiphany/issues/1674#issuecomment-706984742_

**Comment by sk4zuzu** [comment]
> * Test report file name is `repot.xml`, shouldn't it be `report.xml`?
The report file name still needs to be fixed.

> * No description about dependencies that should be installed to run tests, such as `go`, `go-junit-report`, `yq`.
> * Licenses information is not updated according to the point above.
We have "dependencies" section in readme, but it's incomplete, needs to be extended.

**Comment by atsikham** [comment]
Discussed with @seriva that what we have in dependencies is enough.
