### ISSUE TITLE
Rewrite module tests into Golang 

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-azure-basic-infrastructure#27]
To allow reach tests logic and to not use bash magic in `make test`.

**Comment by mkyc** [comment]
Implementation in #34 

![Screenshot 2020-10-21 at 17 49 31](https://user-images.githubusercontent.com/28505782/96745402-61313800-13c6-11eb-9958-9fe509478b35.png)

**Comment by mkyc** [comment]
Tests have passed also after merge to develop. 

![Screenshot 2020-10-28 at 13 04 31](https://user-images.githubusercontent.com/28505782/97433716-3c851500-191e-11eb-89b7-f77dd2d9bdd8.png)

**Comment by atsikham** [comment]
Tested and verified by me, moving to DoD.
