### ISSUE TITLE
Add the ability to customize system disk size

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/m-azure-basic-infrastructure#28]
**Is your feature request related to a problem? Please describe.**
All VMs that are created by the module have always OS disk with 32 GB. This may be not enough (in long term) at least for repository machine where 64 GB is preferred. Need to add an ability to configure the disk size.

**Describe the solution you'd like**
Add module's parameter(s) to define disk size

```
init: setup
	@docker run --rm \
		-v $(ROOT_DIR)/shared:/shared \
		-t $(AZBI) \
		init \
		M_VMS_COUNT=2 \
		M_PUBLIC_IPS=false \
		M_NAME=$(M_NAME) \
		M_VMS_RSA=$(VMS_RSA_FILENAME) \
		M_VMS_DISK_SIZE=$(VMS_DISK_SIZE) 
...
```

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by mkyc** [comment]
@to-bar wouldn't it be better to add next data disk and keep root disk just for OS?

**Comment by to-bar** [comment]
> 
> 
> @to-bar wouldn't it be better to add next data disk and keep root disk just for OS?

Keeping OS data on separate disk is a good practice 👍

**Comment by mkyc** [comment]
@to-bar @atsikham one more question here: do we want to specify mount point as well? My opinion is yes, but I'd like confirmation.

**Comment by atsikham** [comment]
@to-bar what do you think? I agree with @mkyc that we can specify mount points here. But it's necessary to figure out how we mount a disk - I see no straightforward way how to do that with Terraform. As @sk4zuzu suggested, It could be done via `null resource` or `cloud init`.
Also there was #42 task as I forgot about this one - the idea there is that it should be configured per VM group.

**Comment by sk4zuzu** [comment]
> ... As @sk4zuzu suggested, It could be done via `null resource` or `cloud init`. ...

To be completely precise, `cloud init` or `null resource` can be used to modify fstab / systemd config and only then should be used to mount the volume. Thanks to that after any reboot / poweroff operations the volume will be mounted again when vm starts. :+1::innocent:

**Comment by mkyc** [comment]
I would go with cloud init provider in case we do it.

**Comment by sk4zuzu** [comment]
> I would go with cloud init provider in case we do it.

Yep, but we should be careful and verify if/what changes to the cloud init template will cause VM recreation. I recall that was the case. :nail_care: It may be ok to recreate, but we should precisely know about it and include it in documentation. :hugs:

**Comment by mkyc** [comment]
From [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine#disk_size_gb): 

> disk_size_gb - (Optional) The Size of the Internal OS Disk in GB, if you wish to vary from the size used in the image this Virtual Machine is sourced from.
NOTE:
If specified this must be equal to or larger than the size of the Image the Virtual Machine is based on. When creating a larger disk than exists in the image you'll need to repartition the disk to use the remaining space.

So my opinion is following: 
 * we should abandon this task and don't change OS disk size at all
 * we should continue with #42 and there add "data disks" with mount points. 

To have any use of os disk resize we would like to repartition it anyway and that sounds like bad idea.

**Comment by sk4zuzu** [comment]
I think I would set this to the value identical as in the provider and used `lifecycle { ignore_changes = [ xxx ] }`, so this would work only during vm/volume creation. Then I would not put this in any examples, just in docs. So then if anybody would like this disk bigger for any reason, then "rebuild the world" strategy would allow that. We would not remove it completely, just restrict its usage and the rationale would be that everybody make mistakes (even guys that write tf providers)... :innocent:

**Comment by mkyc** [comment]
So in general I'm against this strategy. If someone wants to create "any infrastructure" than epiphany is in general not his/her way to go. They should use terraform, ansible and other stuff directly. We should provide LEGO rather than plasticine :)

**Comment by sk4zuzu** [comment]
> So in general I'm against this strategy. If someone wants to create "any infrastructure" than epiphany is in general not his/her way to go. They should use terraform, ansible and other stuff directly. We should provide LEGO rather than plasticine :)

Actually you're limiting your options. This one in particular very simple and basic and should be provided IMO. As for the "use tf directly" I completely agree :+1: :innocent:

**Comment by mkyc** [comment]
I'm not limiting, I'm just not solving unproven need. We can introduce it later if we understand need. Providing possibility just because there is one is not best idea in my opinion.

**Comment by mkyc** [comment]
As discussed privately, data disks are going to be introduced in #42. In this task I'm just going to remove hardcoded value in #61.

**Comment by rpudlowski93** [comment]
I just created infrastructure with some instances in different subnets and I can confirm that the 32GB hardcoded value is removed and os disk size is by default 30GB right now. Only data disk is possible to customize ✅
