### ISSUE TITLE
fix pipeline to be triggered only from organisation members since for tests azure resources are required

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-azure-basic-infrastructure#35]
Current way is possible security issue. 
We should 

Use it like this: https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/pipeline-triggers.md#examples-pr-triggers

Consider to add options:
"allowSecrets":false (DON'T Make secrets available to builds of forks)
"requireCommentsForNonTeamMembersOnly":true

See more info [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers)

**Comment by atsikham** [comment]
Not sure that it's about this task, but probably we also need to update pre commit hook to not allow not follow some code style, for example force to add comments in integration tests to be parsed by [godoc](https://blog.golang.org/godoc).

**Comment by mkyc** [comment]
This task should be done after merge of #47 otherwise it might lead to work being done twice.

**Comment by mkyc** [comment]
@atsikham I created separate issue from your comment.

**Comment by mkyc** [comment]
So PR triggers were already added some time before. 

I wasn't able to find solution for how to exclude forks triggering pipelines in YAML, so I filed [this issue](https://developercommunity2.visualstudio.com/t/How-to-configure-shBuildsh-shpul/1304227) and will wait a bit for feedback.

**Comment by mkyc** [comment]
Comment from MS Developer Community: 

> Hi Mateusz Kyc,
> 
> Thank you for posting in Developer Community.
> 
> For YAML pipelines, you still need to check option on UI. There is no YAML syntax to support this currently. Please go to pipeline edit page - > click the three dots in the upper right corner ->click Triggers -> click Pull request validation -> enable Build pull requests from forks of this repository option.
> 
> 
> ![B8f5888808c354e4a906032da2bbe8322637466235895892502_Triggers](https://user-images.githubusercontent.com/28505782/105028379-3ef49800-5a51-11eb-9fae-4458b25873e3.PNG)
> 
> ![B11f5aab6344949169059f34a56cede07637466236030418609_Checkbox](https://user-images.githubusercontent.com/28505782/105028400-45830f80-5a51-11eb-9089-e25a4a2014d9.PNG)
> 
> Hope this can help.

**Comment by mkyc** [comment]
I did exactly what was proposed: 

![Screenshot 2021-01-19 at 12 29 35](https://user-images.githubusercontent.com/28505782/105033531-89c5de00-5a58-11eb-8e0d-f6b6af7f4c95.png)

So right now PR's from forks would not even trigger build.

**Comment by przemyslavic** [comment]
✅ The option to exclude PR building from forks has been set on UI.
