### ISSUE TITLE
Unify docker image name across module

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-azure-basic-infrastructure#38]
**Is your feature request related to a problem? Please describe.**
Currently we have multiple places with image name and tag. We should unify it to have one single place to update it.
**Describe the solution you'd like**
Check integration [tests](https://github.com/epiphany-platform/m-azure-basic-infrastructure/blob/develop/integration_test.go). There is an image name and tag specified and it may be the cause to run tests not with the latest changes. Suggestion here is to set tag as a variable and pass to tests execution. Check AWS module [tests](https://github.com/epiphany-platform/m-aws-basic-infrastructure/blob/develop/tests/integration_test.go) and [pipeline](https://github.com/epiphany-platform/m-aws-basic-infrastructure/blob/develop/pipeline.yml) to see how it's done there.
If there is something to update in documentation about tests execution, it should be updated.
**Describe alternatives you've considered**
No.
**Additional context**
Original description:
> If there are a few places to specify the same thing, person who releases module, should do it carefully, or we will have wrong tests after release as a result. With increasing modules count and not automated release process we may have problems with that.

_Originally posted by @atsikham in https://github.com/epiphany-platform/m-azure-basic-infrastructure/pull/34#discussion_r513343882_

**Comment by przemyslavic** [comment]
Tested:
✅ `make build`
✅ `make test`
✅ `make pipeline-test`.
