### ISSUE TITLE
make output more verbose

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-azure-basic-infrastructure#51]
No logs visible when running commands. The only output I can see is as follows (basically it only shows the comparison of the state file and its final contents):
```
user@xxx$ make plan
Planned changes:
  &v0.State{
        Kind:    &"state",
        Version: &"v0.0.1",
        Unused:  {},
        AzBI: &v0.AzBIState{
                Status: "applied",
                Config: &v0.Config{
                        Kind:    &"azbi",
                        Version: &"v0.0.2",
                        Params: &v0.Params{
                                Name:        &"qa-azbi-test",
-                               VmsCount:    &1,
+                               VmsCount:    &2,
                                UsePublicIP: &true,
                                Location:    &"northeurope",
                                ... // 3 identical fields
                        },
-                       Unused: nil,
+                       Unused: []string{},
                },
                Output: &{PrivateIps: {"10.0.1.4"}, PublicIps: {"xx.xx.xx.xx"}, RgName: &"qa-azbi-test-rg", VmNames: {"qa-azbi-test-sub0-0"}, ...},
        },
  }

Will perform following changes:
        Add: 4, Change: 0, Destroy: 0
```
```user@xxx$ make apply
Planned changes:
  &v0.State{
        Kind:    &"state",
        Version: &"v0.0.1",
        Unused:  {},
        AzBI: &v0.AzBIState{
                Status: "applied",
                Config: &v0.Config{
                        Kind:    &"azbi",
                        Version: &"v0.0.2",
                        Params: &v0.Params{
                                Name:        &"qa-azbi-test",
-                               VmsCount:    &1,
+                               VmsCount:    &2,
                                UsePublicIP: &true,
                                Location:    &"northeurope",
                                ... // 3 identical fields
                        },
-                       Unused: nil,
+                       Unused: []string{},
                },
                Output: &{PrivateIps: {"10.0.1.4"}, PublicIps: {"xx.xx.xx.xx"}, RgName: &"qa-azbi-test-rg", VmNames: {"qa-azbi-test-sub0-0"}, ...},
        },
  }

State after apply:
{
        "kind": "state",
        "version": "v0.0.1",
        "azbi": {
                "status": "applied",
                "config": {
                        "kind": "azbi",
                        "version": "v0.0.2",
                        "params": {
                                "name": "qa-azbi-test",
                                "vms_count": 2,
                                "use_public_ip": true,
                                "location": "northeurope",
                                "address_space": [
                                        "10.0.0.0/16"
                                ],
                                "subnets": [
                                        {
                                                "name": "sub0",
                                                "address_prefixes": [
                                                        "10.0.1.0/24"
                                                ]
                                        },
                                        {
                                                "name": "sub1",
                                                "address_prefixes": [
                                                        "10.0.11.0/24"
                                                ]
                                        },
                                        {
                                                "name": "sub2",
                                                "address_prefixes": [
                                                        "10.0.21.0/24"
                                                ]
                                        }
                                ],
                                "rsa_pub_path": "/shared/vms_rsa.pub"
                        }
                },
                "output": {
                        "private_ips": [
                                "10.0.1.4",
                                "10.0.1.5"
                        ],
                        "public_ips": [
                                "xx.xx.xx.xx",
                                "yy.yy.yy.yy"
                        ],
                        "rg_name": "qa-azbi-test-rg",
                        "vm_names": [
                                "qa-azbi-test-sub0-0",
                                "qa-azbi-test-sub0-1"
                        ],
                        "vnet_name": "qa-azbi-test-vnet"
                }
        }
}
Performed following changes:
        Add: 4, Change: 0, Destroy: 0
```

And it is even worse for `destroy` command. I wait a few minutes for any result and during that time I don't know what's going on.
```
user@xxx$ time make destroy
Performed following changes:
        Add: 0, Change: 0, Destroy: 14

real    4m48.745s
user    0m0.000s
sys     0m0.063s
```

_Originally posted by @przemyslavic in https://github.com/epiphany-platform/m-azure-basic-infrastructure/issues/14#issuecomment-752536183_

**Comment by rafzei** [comment]
The default output should show some basic information (but more than "Performed following changes") but there should be option to run commands with --debug flag to see detailed output.

**Comment by ar3ndt** [comment]
This is not really as straightforward as it might seem to be.

`2021-02-03T19:42:05Z WRN go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:39 > 2021/02/03 19:42:05 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.`

This part that only TRACE log level should be used to get Terraform's internal logs. Moreover setting TF_LOG to INFO actually doesnt work like it should presenting WRN level..

`-e TF_LOG="INFO" `

`2021-02-03T19:46:32Z WRN go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:39 > 2021/02/03 19:46:32 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
2021-02-03T19:46:32Z WRN go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:39 >   Use TF_LOG=TRACE to see Terraform's internal logs.
2021-02-03T19:46:32Z WRN go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:39 >   ----
2021-02-03T19:46:32Z WRN go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:39 > 2021/02/03 19:46:32 [INFO] Terraform version: 0.13.2  
2021-02-03T19:46:32Z WRN go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/common.go:39 > 2021/02/03 19:46:32 [INFO] Go runtime version: go1.14.7
`

Lets discuss what should we do with that.

**Comment by atsikham** [comment]
@mkyc could you take a look at the last comment?

**Comment by mkyc** [comment]
So in general this is not about terraform logging but about module not passing enough logs in default mode.  

If you run module withhout `--debug` flag, you'll get similar output to what @przemyslavic mentioned in this issue. But if you run it with `--debug` flag, you'll get all the logs you want in realtime. So the thing is to add part of logs to normal mode to show user that automation is doing something and it didn't hang. 

Problem with this task is that terraform logs are shown on "INFO" level with Buch of other things. I'd need to spend some time with code to decide how to do it the best way.

**Comment by ar3ndt** [comment]
Ok it is ready for review. By the way I added more options:

> zerolog allows for logging at the following levels (from highest to lowest):
> 
>     panic (zerolog.PanicLevel, 5)
>     fatal (zerolog.FatalLevel, 4)
>     error (zerolog.ErrorLevel, 3)
>     warn (zerolog.WarnLevel, 2)
>     info (zerolog.InfoLevel, 1)
>     debug (zerolog.DebugLevel, 0)
>     trace (zerolog.TraceLevel, -1)

**Comment by przemyslavic** [comment]
`Panic`, `fatal`, `error`, `warn`, `info`, `debug` and `trace` logging levels have been introduced with the default `info` level.
Now we can see exactly what is happening while executing specific commands.
