### ISSUE TITLE
create NSG for each subnet

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-azure-basic-infrastructure#52]
The ability to create multiple subnets has recently been introduced. At this point, only one security group is created, but it is not associated to any subnet. The goal of this task is to create a security group for each subnet and associate it to that subnet.

**To reproduce:**

1. Run azbi module with the following config:

```json
{
	"kind": "azbi",
	"version": "v0.0.2",
	"params": {
		"name": "qa-azbi-test",
		"vms_count": 1,
		"use_public_ip": true,
		"location": "northeurope",
		"address_space": [
			"10.0.0.0/16"
		],
		"subnets": [
			{
				"name": "sub0",
				"address_prefixes": [
					"10.0.1.0/24"
				]
			},
			{
				"name": "sub1",
				"address_prefixes": [
					"10.0.11.0/24"
				]
			},
			{
				"name": "sub2",
				"address_prefixes": [
					"10.0.21.0/24"
				]
			}			
		],
		"rsa_pub_path": "/shared/vms_rsa.pub"
	}
}
```

2. Verify the created security groups and their associations with the subnets.

_Originally posted by @przemyslavic in https://github.com/epiphany-platform/m-azure-basic-infrastructure/issues/14#issuecomment-752536183_

**Comment by przemyslavic** [comment]
@ar3ndt @mkyc If I'm not mistaken, this task was to create an NSG for each subnet. What we have now is just one security group, regardless of the number of subnets, that is associated to all subnets. So how should this be done?

**Comment by mkyc** [comment]
Hmmmm ... I think you're right and this PR does NOT solve this task actually.

**Comment by ar3ndt** [comment]
It was a comment in PR to actually change this. Initially there were separate nsg for each subent and was decided to use just one...

**Comment by przemyslavic** [comment]
@mkyc there is a comment from @atsikham: https://github.com/epiphany-platform/m-azure-basic-infrastructure/pull/69#discussion_r568429178.
So, should I assume that this task meets the requirements? 😆

**Comment by mkyc** [comment]
Ah sorry, I didn't notice this conversation between @atsikham and @ar3ndt. Also this task is being created after one of your comments @przemyslavic so I guess you're the best person to decide if that is good enough or should be implemented as it was asked in task.

**Comment by przemyslavic** [comment]
OK, then for me at this point it is sufficient to have one security group assigned to multiple subnets.

**Comment by atsikham** [comment]
@przemyslavic @mkyc @ar3ndt I commented so as see no reason to create different security groups with completely the same rules. But I would like to have it configurable, be able to specify different NSGs in configuration and then assign them to specified subnets. Now we don't have such ability and probably there is no such a requirement. WDYT?

**Comment by mkyc** [comment]
In future it will emerge on it's own. We will want to have 22 exposed from all machines and 443 just from one vm-group. But I do not feel a need to create separate requirement for it right now. I believe that when requirement will come we will create issue to extend functionality then.
