### ISSUE TITLE
Add "push image" to pipeline.yml

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-azure-basic-infrastructure#60]
**Is your feature request related to a problem?**
In our [pipelines](https://github.com/epiphany-platform/m-azure-basic-infrastructure/blob/develop/pipeline.yml) we only building and testing code

**Describe the solution you'd like**
When we run our pipelines when some change appears on [develop](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml) branch, we would like to push built image to docker registry. We would like to use YAML [docker task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops)
 
for example:
```
- task: Docker@2
displayName: 'Build and Push Image'
inputs:
containerRegistry: $(registry_name)
command: buildAndPush
repository: $(REPOSITORY_NAME)/$(IMAGE_NAME)
tags: $(MAJOR_VERSION).$(Build.BuildId)
Dockerfile: $(System.DefaultWorkingDirectory)/Dockerfile
buildContext: $(System.DefaultWorkingDirectory)
```
**Describe alternatives you've considered**

**Additional context**

**Comment by przemyslavic** [comment]
Checked the pipeline. If there are any changes made to the develop branch, the image is tagged with `BuildId` and pushed to the Azure container registry.
