### ISSUE TITLE
Add possibility to configure data disks storage type

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-azure-basic-infrastructure#64]
**Is your feature request related to a problem? Please describe.**
Make "os_disk" setting of azurerm_linux_virtual_machine resource configurable.

**Describe the solution you'd like**
Configurable setting and modified tests for that.

**Describe alternatives you've considered**
No.

**Additional context**
How about making this setting configurable? https://docs.microsoft.com/en-us/azure/virtual-machines/disks-types

_Originally posted by @to-bar in https://github.com/epiphany-platform/m-azure-basic-infrastructure/pull/62#r560268061_

**Comment by mkyc** [comment]
Required changes to e-structures should be introduced together with tasks #15 and #45

**Comment by przemyslavic** [comment]
:heavy_check_mark: Tested storage types: `Standard_LRS`, `Premium_LRS`, `StandardSSD_LRS`
:heavy_check_mark: `make test`
:heavy_check_mark: executed Azure DevOps pipeline

❌ Additional changes are required to support the use of `UltraSSD_LRS` disks (created issue #92).
