### ISSUE TITLE
[BUG] Cannot reapply the configuration after it has been changed

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/m-azure-basic-infrastructure#75]
**Describe the bug**
I am unable to reapply the configuration after making some changes to the `azbi-config.json` file.

**How to reproduce**
1. Execute `init`, `plan` and `apply` commands.
2. Make some changes to `azbi-config.json` file.
3. Execute  `plan` command.
4. Execute  `apply` command.

**Expected behavior**
The new configuration has been applied.

**Additional context**
It fails with error:
```
2021-02-24T13:01:16Z FTL go/src/github.com/epiphany-platform/m-azure-basic-infrastructure/cmd/apply.go:53 > incorrect state error="unexpected state: applied"
```

**Comment by mkyc** [comment]
State check in apply command is too strict. It's probably required to remove following check at all:

```golang
if !reflect.DeepEqual(state.AzBI, &st.AzBIState{}) && state.AzBI.Status != st.Initialized && state.AzBI.Status != st.Destroyed {
	logger.Fatal().Err(errors.New(string("unexpected state: " + state.AzBI.Status))).Msg("incorrect state")
}
```

**Comment by mkyc** [comment]
Related to issue: https://github.com/epiphany-platform/e-structures/issues/10

**Comment by atsikham** [comment]
This task can be done independently from https://github.com/epiphany-platform/e-structures/issues/10.

**Comment by przemyslavic** [comment]
:heavy_check_mark: Fixed. Now we can modify the configuration many times and apply it again with no issues.
