### ISSUE TITLE
[FEATURE REQUEST] Utilise `go vendor` to prevent dependencies downloading every build

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-azure-basic-infrastructure#78]
**Is your feature request related to a problem? Please describe.**
Current build process in docker has `go get` step and every build all the dependencies are being downloaded every build. 

**Describe the solution you'd like**
We could utilise `go vendor` command to have all dependencies downloaded on host machine and then just mount `vendor` directory. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by mkyc** [comment]
this is done in #89

**Comment by przemyslavic** [comment]
Added the `go mod vendor` command which is run before the `docker build` command.
