### ISSUE TITLE
[FEATURE REQUEST] Adjust resources names according to naming convention

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-azure-basic-infrastructure#81]
**Is your feature request related to a problem? Please describe.**
currently resources names do not adhere to naming convention

**Describe the solution you'd like**
Fix names. Also discuss update process. 

**Describe alternatives you've considered**
n/a

**Additional context**
Naming convention: https://github.com/epiphany-platform/epiphany/blob/develop/docs/design-docs/infrastructure/naming-convention.md

**Comment by przemyslavic** [comment]
Resource names have been changed to follow the naming pattern `<prefix>-<resource_type>-<index>`.
The name `azbi-auto-test` is used in automatic tests.
